:dart::pencil: add benchmark files for quarter circle isoparametric
cb-geo/mpm-benchmarks pull request #18
Opened 2020-10-04 16:48 UTC by jgiven100

**Describe the PR**
* Add benchmark files for 10m and 30m plate with hole model (isoparametric)
* Update `README.md`

**Related Issues/PRs**
https://github.com/cb-geo/mpm-doc/pull/50

**Additional context**
n/a

2020-10-06 21:39 UTC, kks32 requested changes
could you please add results to an ipynb file?

2020-10-06 22:44 UTC, jgiven100 commented
@kks32 
* added `results.ipynb` for the 10m and 30m models
* files include min and max cartesian stresses at begining, intermediate, and final timesteps for the associated and non-associated analysis
* I was thinking to do radial and hoop stresses instread of cartesian stresses, but that requires a quite a bit more post-processing than what the existing `results.ipynb` seemed to have


Please let me know what else to add to these notebooks

2020-10-07 11:28 UTC, kks32 requested changes

2020-10-07 11:28 UTC, kks32 commented on 2d/plate_with_hole/isoparametric/10m/mpm_nonassociated.json
> +    "uuid": "testing_nonassociated_",
Could we have these as `nonassociated` and `associated`? correspondingly please change ipynb file too.

2020-10-07 15:26 UTC, kks32 commented
@jgiven100 it would be good to add the radial and hoop stresses, we can compute those from the normal stress components.

2020-10-12 22:39 UTC, jgiven100 commented
> @jgiven100 it would be good to add the radial and hoop stresses, we can compute those from the normal stress components.

@kks32 Are you thinking loop through all material points to find max `sigma_rr` and `sigma_tt` or just pick an internal point and show polar stress for reference

2020-10-14 20:48 UTC, kks32 commented
@jgiven100 just a selected internal point.

2020-10-14 22:36 UTC, jgiven100 commented
@kks32 
* `testing_` removed from `mpm-input.json` filenames and corresponding `results.ipynb` files
* `results.ipynb` include radial and hoop stress for internal material point 

(sorry that took 3 commits)

2020-10-16 13:39 UTC, kks32 approved these changes

2020-10-16 13:39 UTC, merged

2020-10-16 13:39 UTC, kks32 commented
Thank you @jgiven100 !